sonar.projectKey=apae-gestao-escolar-frontend
sonar.projectName=APAE Gestão Escolar - Frontend
sonar.sources=src
sonar.exclusions=**/node_modules/**, **/.next/**, public/**, **/next-env.d.ts, src/components/ui/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8
