name: Docker Build & Publish

on:
  push:
    branches:
      - dev
      - dev-database
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  publish-backend:
    name: Build & publish backend
    uses: IFPBEsp/APAE-INFRA/.github/workflows/docker-build-publish-image.yml@dev
    with:
      context: ./api
      dockerfile: ./api/Dockerfile
      image-name: apae-gestao-escolar-backend
      platforms: '["linux/amd64"]'
      scan-severity: "HIGH,CRITICAL"

  publish-frontend:
    name: Build & publish frontend
    uses: IFPBEsp/APAE-INFRA/.github/workflows/docker-build-publish-image.yml@dev
    with:
      context: ./app
      dockerfile: ./app/Dockerfile
      image-name: apae-gestao-escolar-frontend
      build-args: |
        NEXT_PUBLIC_API_URL=/gestao-escolar/api
      platforms: '["linux/amd64"]'
      scan-severity: "HIGH,CRITICAL"
