name: Flyway Migrations Validate

on:
  pull_request:
    paths:
      - "api/src/main/resources/db/migration/**"
      - ".github/workflows/flyway-validate.yml"
      - ".scripts/db/apae-geral-contract.sql"

permissions:
  contents: read
  pull-requests: read

jobs:
  flyway:
    name: Validate Flyway migrations
    uses: IFPBEsp/APAE-INFRA/.github/workflows/flyway-validate-reusable.yml@58-ci-criar-workflow-reutilizavel-para-validacao-de-migrations-do-flyway-dos-repositorios-da-apae
    with:
      migrations-path: "api/src/main/resources/db/migration"
      extra-migrations-paths: |
        .scripts/db/apae-geral-contract.sql
      schemas: "gestao_escolar"
      postgres-version: "15"
      flyway-version: "9.22.3"
      check-upgrade-path: true
      fail-on-destructive: false
